- name: Ensure nginx is installed
  package:
    name: nginx
    update_cache: yes

- name: Create directories for TLS certificates
  file:
    path: "{{ tls_dir }}"
    state: directory
    mode: '0750'
  notify: Restart nginx

- name: Copy TLS files
  copy:
    src: "{{ item }}"
    dest: "{{ tls_dir }}"
    mode: '0600'
  loop:
    - "{{ key_file }}"
    - "{{ cert_file }}"
  notify: Restart nginx
  
- name: Manage nginx config template
  template:
    src: nginx.conf.j2
    dest: "{{ conf_file }}"
    mode: '0644'
  notify: Restart nginx

- name: Enable configuration
  file:
    dest: /etc/nginx/sites-enabled/default
    src: /etc/nginx/sites-available/default
    state: link

- name: Install home page
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    mode: '0644'

- name: Restart nginx
  meta: flush_handlers

- name: "Test it! https://{{ ansible_host }}/index.html"
  delegate_to: localhost
  become: false
  uri:
    url: 'https://{{ ansible_host }}/index.html'
    validate_certs: false
    return_content: true
  register: this
  failed_when: "'Running on ' not in this.content"
  tags:
    - test