apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: {{.Values.namespace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3NpbXBsZWFkZHJlc3MucnU6NTA1MCI6ewogICAgICAgICAgICAidXNlcm5hbWUiOiJnaXRsYWItY2ktdG9rZW4iLAogICAgICAgICAgICAicGFzc3dvcmQiOiJYOGdHcDc3OHRCZ1h2VVEza05rWCIKICAgIAl9CiAgICB9Cn0=