- name: install redis
  package:
    state: present
    name: redis-server

- name: add our redis service
  copy:
    src: redis.service
    dest: /etc/systemd/system/redis.service
    owner: root
    group: root
    mode: '644'
    follow: yes

- name: Restart redis
  systemd:
    name: redis
    daemon_reload: true
    enabled: true
    state: restarted