---
#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: petrovyh
  labels:
    app: my_app
    another_label: some_data


---
#DeploymentSet
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: petrovyh
  labels:
    app: my_app
    another_label: some_data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my_app
      another_label: some_data
  template:
    metadata:
      labels:
        app: my_app
        another_label: some_data
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
          - name: SOME_ALLOWED
            valueFrom:
              configMapKeyRef:
                name: first-config-map
                key: some_allowed
        volumeMounts:
          - name: config
            mountPath: "/config"
            readOnly: true
          - name: secret
            mountPath: /etc/secret-volume
            readOnly: true
        ports:
        - containerPort: 5000
          protocol: TCP
          name: http
        resources:
          limits:
            cpu: 50m
            memory: 20Mi
          requests:
            cpu: 50m
            memory: 20Mi
      volumes:
      - name: config
        configMap:
          name: first-config-map
          items:
          - key: "game.properties"
            path: "game.properties"
      - name: secret
        secret:
          secretName: firstsecret

---
#Service
apiVersion: v1
kind: Service
metadata:
  namespace: petrovyh
  name: my-app-service
  labels:
    app: my_app
    another_label: some_data
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: my_app
    another_label: some_data
  type: ClusterIP


---
#ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: first-config-map
  namespace: petrovyh
data:
  some_allowed: 'true'
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30

---
#Secret
apiVersion: v1
kind: Secret
metadata:
  name: firstsecret
  namespace: petrovyh
data:
  user: YWRtaW4K
  pass: YWRtaW4K